# Generated by Django 5.0.2 on 2024-02-15 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('appliedPosition', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('gpa', models.FloatField()),
                ('linkedIn', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
            ],
        ),
    ]
