# Generated by Django 5.0.2 on 2024-02-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InterviewFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cv',
            field=models.CharField(default='www.google.com', max_length=255),
            preserve_default=False,
        ),
    ]
